### ISSUE TITLE
ViZDoom's Development Roadmap

### ISSUE THREAD

**Issue by mwydmuch** [Farama-Foundation/ViZDoom#546]
This is a loose roadmap of our plans for the further development of ViZDoom. It assumes the slowest possible progress. 

**Items marked as `(help wanted)` can be picked up by volunteers earlier.**
If you would like to contribute join our discord server https://discord.gg/bnJ6kubTg6 and put a message in the new contributes channel with any particular topics that you would like to work.

**August - documentation improvements:**
- [ ] Documentation for Gymnasium wrapper
- [ ] Add tutorial on creating custom environments
- [ ] Overall polish of the documentation
- [ ] Test and improve all the examples **(help wanted)**

**September/October - installation/distribution improvements:**
- [ ] Manylinux wheels
- [ ] Condo package (help needed)
- [ ] ViZDoom reaching mature Farama environment status

**November/December - multi-agent environments:**
- [ ] PettingZoo wrapper/support for easier support for multi-agent environments **(help wanted)**
- [ ] Create examples of multiplayer environments for the PettingZoo wrapper **(help wanted)**

Items without a timeline
- [ ] Add support for leading environments configs from the dictionary of keys/strings (help wanted, good first task)
- [ ] Replace Windows DirectDraw backend with SDL2 like on Linux and macOS, (possible fix for https://github.com/Farama-Foundation/ViZDoom/issues/545 and https://github.com/Farama-Foundation/ViZDoom/issues/504) (help wanted)

**Comment by ConnorObrian** [comment]
Hey - are there plans to add Python 3.13 support? :)

**Comment by mwydmuch** [comment]
Yes, I'm going to work on the project in the upcoming week or two. It will definitely get Python 3.13 support.

**Comment by mwydmuch** [comment]
Closing this one, new roadmap available in https://github.com/Farama-Foundation/ViZDoom/issues/706
