### ISSUE TITLE
Checklist for Maturity

### ISSUE THREAD

**Issue by mwydmuch** [Farama-Foundation/ViZDoom#548]
Checklist for Maturity

- [x] Fully deterministic (as far as possible, only animated textures behave in non-deterministic way)
- [x] Explicit Versioning
- [x] Farama Notifications
- [x] PyPI
- [x] Full Package Description
- [x] Deploy via GH Actions
- [x] Website
- [x] Linux and MacOS
- [x] Precommit
- [x] Typehinting
- [x] Docstrings
- [x] CI Testing
- [x] Logo
- [x] CoC
- [x] Gymnasium/PettingZoo API
- [x] JKTerry and Mark as owners
- [x] TOTP
- [x] Google Analytics
- [x] License
- [x] Donations
